<<<<<<< Updated upstream
# Generated by Django 4.2.5 on 2023-09-26 21:58
=======
# Generated by Django 4.2.5 on 2023-10-04 18:02
>>>>>>> Stashed changes

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('email', models.TextField(null=True)),
                ('password', models.CharField(max_length=16)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')])),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
<<<<<<< Updated upstream
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.categoria')),
            ],
        ),
=======
                ('stock', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.producto')),
            ],
        ),
>>>>>>> Stashed changes
    ]
