# Generated by Django 4.2.5 on 2023-10-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_orden',
            name='orden',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detalle_orden',
            name='producto',
            field=models.PositiveIntegerField(),
        ),
    ]
