# Generated by Django 4.2.5 on 2023-09-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_tipo_remove_producto_cantidad_orden_detalle_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orden',
            name='receptor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
