# Generated by Django 4.2.5 on 2023-09-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_alter_orden_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='receptor',
            field=models.IntegerField(choices=[(1, 'Salida'), (2, 'Entrada')]),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.IntegerField(),
        ),
    ]
