# Generated by Django 4.2.5 on 2023-09-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_alter_orden_receptor_alter_tipo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='receptor',
            field=models.TextField(null=True),
        ),
    ]
