# Generated by Django 4.2.5 on 2023-09-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0012_alter_orden_tipo_alter_tipo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_creacion',
        ),
    ]
