# Generated by Django 4.2.5 on 2023-09-28 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0013_remove_producto_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo',
            name='estado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
